### ISSUE TITLE
offer to take an argument when caller is needed

### ISSUE THREAD

**Issue by chiptus** [edukera/vscode-archetype#6]
when using the extension to transpile FA1.2 to ligo, I get `'caller' is used in initialization of contract, please set caller value with '--set-caller-init'`, would be nice that if this error is thrown, instead of showing the error, the extension will ask for a parameter.

![image](https://user-images.githubusercontent.com/1381655/89725191-9a881780-da15-11ea-9ec2-03f9c19ab698.png)

**Comment by rognierbenoit** [comment]
there is now a parameter for the caller (originator) address in the extension parameters:
<img width="730" alt="Capture d’écran 2020-08-09 à 16 45" src="https://user-images.githubusercontent.com/4006868/89735046-03947d00-da60-11ea-9e35-4525058d9451.png">
(update extension)

**Comment by chiptus** [comment]
nice, thx!
